force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <label>Expected Salary</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/empupdateClass.cls
public  class empupdateClass {

    @AuraEnabled
    public static list<Employee__c> EmployeeRecordsView(){

            list<Employee__c> EmployeeList =[SELECT Id, Name, Education__c, 
            Job_Title__c, Email__c, Skills__c,Expected_Salary__c, 
            Application_Status__c,Phone__c FROM Employee__c];

            return EmployeeList;
            

    }
    @AuraEnabled
    public static void EmployeeRecordsUpdateApproved(Id Applicationid){
        try {

            Employee__c Approvedemp1 =[select id,Application_Status__c from Employee__c where id=:Applicationid];
            Approvedemp1.Application_Status__c='Approved';
            update Approvedemp1;
           
        } catch (Exception e) {
            system.debug(e.getMessage());
        }
    }

    @AuraEnabled
    public static void EmployeeRecordsUpdateRejected(id Applicationid){
        try {
            Employee__c Rejectedemp1 =[select id,Application_Status__c from Employee__c where id=:Applicationid];
            Rejectedemp1.Application_Status__c='Rejected';
            update Rejectedemp1;
            
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
}