force-app/main/default/objects/Sub__c/Sub__c.object-meta.xml
<CustomObject>
    <label>Subscriber</label>
    <nameField>
        <label>Sub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribera</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscribera</relationshipLabel>
    <relationshipName>Subscribera</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sub__c/fields/Recent_Subscriber__c.field-meta.xml
<CustomField>
    <fullName>Recent_Subscriber__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recent Subscriber</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubscriberHelper.cls
public class SubscriberHelper {
    public static void AccountSubMethodTrigger73PWC(list<Sub__c> newlist)
    {
        if(!newlist.isempty())
        {
            set<id> accountid= new set<id>();
            for(Sub__c sub:newlist)
            {
                if(sub.Account__c !=null)
                {
                    accountid.add(sub.Account__c);
                    
                }
            }
            
            if(!accountid.isempty())
            {
                list<Sub__c> newsublist=[select id,Recent_Subscriber__c,Account__c,CreatedDate
                                         from Sub__c where Account__c in: accountid order by 
                                         Account__c, CreatedDate DESC];
                
                map<id,Sub__c> Mostrecentsub = new map<id,sub__c>();
                list<sub__c> updatesub = new list<sub__c>();
                
                if(!newsublist.isempty())
                {
                    for(sub__c sub:newsublist)
                    {
                        if(!Mostrecentsub.containskey(sub.Account__c))
                        {
                            sub.Recent_Subscriber__c=true;
                            Mostrecentsub.put(sub.Account__c,sub);
                            
                        }else
                        {
                            sub.Recent_Subscriber__c=false;
                        }
                        updatesub.add(sub);
                    }
                }
                if(!updatesub.isempty())
                {
                    Database.update(updatesub,false);
                }
            }
        }
    }

}