force-app/main/default/objects/Event_Distribution__c/Event_Distribution__c.object-meta.xml
<CustomObject>
    <label>Event Distribution</label>
    <nameField>
        <label>Event Distribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Distribution__c/fields/Distribution__c.field-meta.xml
<CustomField>
    <fullName>Distribution__c</fullName>
    <label>Distribution</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Distribution__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Distributions</relationshipLabel>
    <relationshipName>Event_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Distribution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/eventdistrubtionhelper.cls
public class eventdistrubtionhelper {
    
    public static void eventfirstmethod(list<Event_Distribution__c> newlist)
    {
        set<id> evetids = new set<id>(); 
        if(newlist !=null)
        {
            for(Event_Distribution__c ed:newlist)
            {
                if(ed.Event__c !=null)
                {
                    evetids.add(ed.Event__c);

                }
                
            }
            
            if(!evetids.isempty())
            {
                system.debug(evetids);
                integer eventcapacitycount=0;
                integer Distributioncount=0;
                integer finalcapacityvalue=0;
                map<id,event__c> eventmap = new map<id,event__c>([select id, Event_Capacity__c from event__c where id in: evetids]);
                system.debug(eventmap);
                list<Event__c> eventupdate = new list<Event__c>();
                
                for(Event_Distribution__c ed:newlist)
                {
                    if(eventmap.containskey(ed.Event__c))
                    {
                        event__c newev=eventmap.get(ed.Event__c);
                        
                        eventcapacitycount=(integer)newev.Event_Capacity__c;
                        Distributioncount=(integer)ed.Distribution__c;
                        if(eventcapacitycount>0)
                        {
                            system.debug(eventcapacitycount);
                            finalcapacityvalue=eventcapacitycount-Distributioncount;
                            system.debug(finalcapacityvalue);
                            newev.Event_Capacity__c=finalcapacityvalue;
                            ed.Status__c='Confirmed';
                            
                        }
                        else{
                            ed.Status__c='Waiting';
                        }
                        eventupdate.add(newev);
                        
                    }
                    
                }
                if(!eventupdate.isempty())
                {
                    update eventupdate;
                }
                
            }
        }
        
    } 
    
}