force-app/main/default/objects/Account/fields/Active_Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Active_Marketplace__c</fullName>
    <label>Active Marketplace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Marketplace__c/Marketplace__c.object-meta.xml
<CustomObject>
    <label>Marketplace</label>
    <nameField>
        <label>Marketplace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketplaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketplace__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Marketplaces</relationshipLabel>
    <relationshipName>Marketplaces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MarketplaceHelperClassTest.cls
@istest
public class MarketplaceHelperClassTest {
    @testsetup
    public static void TestDatafortheMarketPlaceMethods()
    {
        
        Account acc = new Account();
        acc.Name='TestingAccount';
        acc.Description='tharun';
        
        insert acc;
        
        Asset ass = new Asset();
        ass.Name='Testingasset';
        ass.AccountId=acc.id;
        
        Insert ass;
        
        list<Marketplace__c> marketplacelist = new list <Marketplace__c>();
        
        for(integer i=0; i<=3; i++)
        {
            Marketplace__c ma = new Marketplace__c();
            ma.Name='TestingMarketPlace 00'+i;
            ma.Asset__c=ass.Id;
            marketplacelist.add(ma);
            
        }
        
        if(!marketplacelist.isempty())
        {
            Database.SaveResult[] results= Database.Insert(marketplacelist,false);
        }
 
    }
    
    @istest
    public static void testMethod001()
    {
        list<Marketplace__c> malist = [select id,Name,Asset__c from Marketplace__c];
        map<id,Marketplace__c> mamap = new map<id,Marketplace__c>([select id,Name,Asset__c from Marketplace__c]);
        Account acc=[select id,Name,Description from Account];
        map<id,asset> assmap= new map<id,asset>([select id,Name,AccountId from Asset]);

        
        
        test.StartTest();
        MarketplaceHelperClass.afterInsertAndUpdate(malist,mamap);
        Test.StopTest();
        
        Account acc1=[select id,Name,Description,Active_Marketplace__c from Account where Name ='TestingAccount'];
        system.debug(acc1.Name);
        system.debug(acc1.Active_Marketplace__c);
        
        
        
    }

}