force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>An Object to Store car Information</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>This picklist is the category list of cars</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>MUV</fullName>
            </value>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/MRP__c.field-meta.xml
<CustomField>
    <fullName>MRP__c</fullName>
    <label>MRP</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/carControllerClass.cls
public with sharing class carControllerClass {

    public class filters{
        @AuraEnabled
        public string searchKey {get;set;}
        @AuraEnabled
        public Decimal maxPrice {get;set;}
        @AuraEnabled
        public string[] categories {get;set;}
        @AuraEnabled
        public string[] makeType {get;set;}

    }
    @AuraEnabled(cacheable=true)
    public static list<Car__c> carmethod(filters filtershere){
        string key, whereClause='';
        Decimal maxPrice;
        string[] categories, makeType, criteria = new list<string>{};
        if(filtershere != null){
            maxPrice= filtershere.maxPrice;
            categories= filtershere.categories;
            makeType= filtershere.makeType;
            if(!String.isempty(filtershere.searchKey)){
                key= '%'+ filtershere.searchKey + '%';
                criteria.add('Name LIKE :key');
            }
            if(filtershere.maxPrice >=0){
                criteria.add('MRP__c <= :maxPrice');
            }
            if(filtershere.categories != null){
                criteria.add('Category__c IN :categories');
            }
            if(filtershere.makeType != null){
                criteria.add('Make__c IN :makeType');
            }
            if(criteria.size()>0){
                whereClause= ' WHERE ' + String.join(criteria, ' AND ');
            }
        }
        String query= 'SELECT Id, Name, MRP__c, Description__c, Category__c, Picture_URL__c FROM Car__c' + whereClause + ' WITH SECURITY_ENFORCED ORDER BY Name';
        return Database.query(query);

    }
    @AuraEnabled(cacheable=true)
    public static Car__c[] getSimilarCars(Id carId, String[] makeType){
        return [SELECT id,name,MRP__c, Description__c, Category__c, Picture_URL__c FROM Car__c WHERE Make__c IN :makeType AND Id != :carId LIMIT 10];
    }
}